version: "3.8"
services:
  # db:
  #   image: mysql
  #   container_name: "database"
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=swabhav
  #     - MYSQL_DATABASE=swabhav
  #     - MYSQL_USER=swabhav
  #     - MYSQL_PASSWORD=swabhav
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./go
    container_name: "api"
    ports:
      - "8080:8080"
  # angular:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./Student-API
  #   volumes:
  #     - /app/node_modules
  #     - ./Student-API:/app
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
# volumes:
#   database_mysql: