version: "3"
services:
  golang:
    build:
      dockerfile: Dockerfile.dev
      context: ./go
    container_name: golang
    ports:
      - 8080:8080
  angular:
    build:
      dockerfile: Dockerfile.dev
      context: ./Student-API
    container_name: angular
    ports:
      - 3000:80