version: "3.8"
services:
  # db:
  #   image: mysql
  #   container_name: "database"
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=swabhav
  #     - MYSQL_DATABASE=swabhav
  #     - MYSQL_USER=swabhav
  #     - MYSQL_PASSWORD=swabhav
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  golang:
    build:
      dockerfile: Dockerfile.dev
      context: ./go
    container_name: "golang"
    ports:
      - "8080:8080"
  angular:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./Student-API
    container_name: "angular"
    ports:
      - "4200:80"
    volumes:
      - /app/node_modules
      - ./Student-API:/app
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   container_name: "nginx"
  #   # volumes:
  #   #   - /app/dist/Student-API /usr/share/nginx/html
  #   ports:
  #     - '80:80'
# volumes:
#   database_mysql: