# FROM node:10.13-alpine

# WORKDIR /app

# COPY package*.json .
# RUN npm install
# COPY . .

# # EXPOSE 4200

# CMD [ "npm", "run", "start" ]

# Stage 1
FROM node:10-alpine as builder

WORKDIR "/app"

COPY ./package*.json ./
RUN npm install
COPY . .

RUN npm run prod
# CMD [ "npm", "run", "prod" ]

# Stage 2
FROM nginx:1.17.1-alpine

EXPOSE 4200

# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/Student-API /usr/share/nginx/html