# FROM node:10-alpine

# WORKDIR /app

# COPY package*.json .

# RUN npm install

# COPY . .

# CMD [ "npm", "start" ]
# # CMD [ "npm", "run", "prod" ]

FROM node:10-alpine

WORKDIR /app

COPY . /app

RUN npm install

CMD [ "npm", "start" ]
# CMD [ "npm", "run", "prod" ]