# FROM node:10-alpine

# WORKDIR /app

# COPY package*.json .

# RUN npm install

# COPY . .

# # EXPOSE 4201

# CMD [ "npm", "run", "prod" ]

#BELOW CODE WORKS

# Stage 1
FROM node:10-alpine as builder

WORKDIR /app

COPY ./package*.json ./
RUN npm install
COPY . .

RUN npm run prod

# Stage 2
FROM nginx:1.17.1-alpine

EXPOSE 4201

COPY ../nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/Student-API /usr/share/nginx/html