FROM golang:1.17-alpine

WORKDIR /app

COPY go.mod .
# COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o main .

CMD ["/app/main"]


# ======================= FANCY =======================  

# FROM golang:1.17-alpine AS builder

# WORKDIR /app

# ADD go.mod .
# COPY . .

# RUN go build -o backend main.go

# FROM alpine

# WORKDIR /app
# COPY --from=builder /app/backend /app/backend

# CMD ["./backend"]