apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-restapi
  labels:
    app: golang-restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-restapi
  template:
    metadata:
      name: backend-pod
      labels:
        app: golang-restapi
    spec:
      containers:
        - name: golang-restapi
          image: shaileshswabhav/restapi
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: golang-restapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081